version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_DATABASE: 'daedongbap_map'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./daedongbap_map.sql:/docker-entrypoint-initdb.d/daedongbap_map.sql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URI: mysql+pymysql://root:0000@db/daedongbap_map

volumes:
  db_data:
